DECLARE @SQL NVARCHAR(MAX) = '
ALTER DATABASE '+DB_NAME()+' SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE '+DB_NAME()+' SET ENABLE_BROKER;
ALTER DATABASE '+DB_NAME()+' SET MULTI_USER;'
EXEC (@SQL)
